			//   Basic Tokens		
#define tknAND 0x80
#define tknDIV 0x81
#define tknEOR 0x82
#define tknMOD 0x83
#define tknOR 0x84
#define tknERROR 0x85
#define tknLINE 0x86
#define tknOFF 0x87
#define tknSTEP 0x88
#define tknSPC 0x89
#define tknTAB 0x8A
#define tknELSE 0x8B
#define tknMissing 0x8D
#define tknLineNo 0x8D
#define tknOPENIN 0x8E
#define tknTHEN 0x8C
#define tknPTR 0x8F
#define tknPAGE 0x90
#define tknTIME 0x91
#define tknLOMEM 0x92
#define tknHIMEM 0x93
#define tknABS 0x94
#define tknACS 0x95
#define tknADVAL 0x96
#define tknASC 0x97
#define tknASN 0x98
#define tknATN 0x99
#define tknBGET 0x9A
#define tknCOS 0x9B
#define tknCOUNT 0x9C
#define tknDEG 0x9D
#define tknERL 0x9E
#define tknERR 0x9F
#define tknEVAL 0xA0
#define tknEXP 0xA1
#define tknEXT 0xA2
#define tknFALSE 0xA3
#define tknFN 0xA4
#define tknGET 0xA5
#define tknINKEY 0xA6
#define tknINSTR 0xA7
#define tknINT 0xA8
#define tknLEN 0xA9
#define tknLN 0xAA
#define tknLOG 0xAB
#define tknNOT 0xAC
#define tknOPENUP 0xAD
#define tknOPENOUT 0xAE
#define tknPI 0xAF
#define tknPOINT 0xB0
#define tknPOS 0xB1
#define tknRAD 0xB2
#define tknRND 0xB3
#define tknSGN 0xB4
#define tknSIN 0xB5
#define tknSQR 0xB6
#define tknTAN 0xB7
#define tknTO 0xB8
#define tknTRUE 0xB9
#define tknUSR 0xBA
#define tknVAL 0xBB
#define tknVPOS 0xBC
#define tknCHR 0xBD
#define tknGETDollar 0xBE
#define tknINKEYDollar 0xBF
#define tknLEFT 0xC0
#define tknMID 0xC1
#define tknRIGHT 0xC2
#define tknSTR 0xC3
#define tknSTRING 0xC4
#define tknEOF 0xC5
#define tknAUTO 0xC6
#define tknDELETE 0xC7
#define tknLOAD 0xC8
#define tknLIST 0xC9
#define tknNEW 0xCA
#define tknOLD 0xCB
#define tknRENUMBER 0xCC
#define tknSAVE 0xCD
#define tknEDIT 0xCE
#define tknPTRc 0xCF
#define tknPAGESet 0xD0
#define tknTIMESet 0xD1
#define tknLOMEMSet 0xD2
#define tknHIMEMSet 0xD3
#define tknSOUND 0xD4
#define tknBPUT 0xD5
#define tknCALL 0xD6
#define tknCHAIN 0xD7
#define tknCLEAR 0xD8
#define tknCLOSE 0xD9
#define tknCLG 0xDA
#define tknCLS 0xDB
#define tknDATA 0xDC
#define tknDEF 0xDD
#define tknDIM 0xDE
#define tknDRAW 0xDF
#define tknEND 0xE0
#define tknENDPROC 0xE1
#define tknENVELOPE 0xE2
#define tknFOR 0xE3
#define tknGOSUB 0xE4
#define tknGOTO 0xE5
#define tknGCOL 0xE6
#define tknIF 0xE7
#define tknINPUT 0xE8
#define tknLET 0xE9
#define tknLOCAL 0xEA
#define tknMODE 0xEB
#define tknMOVE 0xEC
#define tknNEXT 0xED
#define tknON 0xEE
#define tknVDU 0xEF
#define tknPLOT 0xF0
#define tknPRINT 0xF1
#define tknPROC 0xF2
#define tknREAD 0xF3
#define tknREM 0xF4
#define tknREPEAT 0xF5
#define tknREPORT 0xF6
#define tknRESTORE 0xF7
#define tknRETURN 0xF8
#define tknRUN 0xF9
#define tknSTOP 0xFA
#define tknCOLOR 0xFB
#define tknTRACE 0xFC
#define tknUNTIL 0xFD
#define tknWIDTH 0xFE
#define tknOSCLI 0xFF
